name: more_recipes
main: cn.navy_master.recipes.MoreRecipes
version: 1.0.0
api-version: 1.13
author: navy_master
commands:
  sethome:
    description: set the home of you
    usage: /<command>
  home:
    description: back to the home of you
    usage: /<command>
  assemble:
    description: call everyone tp to you
    usage: /<command>
  response:
    description: tp to the assemble place
    usage: /<command>